[package]
name = "rusty-wam"
version = "0.7.6"
authors = ["Mark Thom"]

[dependencies]
lazy_static = "0.2"
num = "0.1"
regex = "0.2.1"
ordered-float = "0.5.0"
downcast = "0.9.1"

[dependencies.termion]
version = "1.4.0"