[package]
name = "rusty-wam"
version = "0.6.5"
authors = ["Mark Thom"]

build = "build.rs"

[dependencies]
regex = "0.2.1"

[dependencies.termion]
version = "1.4.0"

[dependencies.lalrpop-util]
version = "0.13.1"

[build-dependencies.lalrpop]
version = "0.13.1"