[package]
name = "rusty-wam"
version = "0.3.0"
authors = ["Mark Thom"]

build = "build.rs"

[dependencies]

[dependencies.lalrpop-util]
version = "0.12.5"

[build-dependencies.lalrpop]
version = "0.12.5"