[package]
name = "rusty-wam"
version = "0.7.0"
authors = ["Mark Thom"]

[dependencies]
lazy_static = "0.2"
num = "0.1"
regex = "0.2.1"
ordered-float = "0.5.0"

[dependencies.termion]
version = "1.4.0"